GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "test",
    "author": "Matti Meikäläinen",
    "url": "https://kela.fi",
    "likes": 1
}

###

//DELETE http://localhost:3003/api/blogs